apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-elasticsearch
  namespace: order-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-elasticsearch
  template:
    metadata:
      labels:
        app: order-elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-elasticsearch
  namespace: order-platform
spec:
  selector:
    app: order-elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
