apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-postgres
  namespace: order-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-postgres
  template:
    metadata:
      labels:
        app: order-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: orders
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: order-postgres
  namespace: order-platform
spec:
  selector:
    app: order-postgres
  ports:
    - port: 5432
      targetPort: 5432
