input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
  }
  mutate {
    remove_field => ["agent", "ecs", "input", "log", "@version"]
  }
}

output {
  elasticsearch {
    hosts => ["http://order-elasticsearch:9200"]
    index => "order-platform-logs-%{+YYYY.MM.dd}"
  }
}
